server:
  port: 8090
  
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/english_db
    username: "english_user"
    password: "english$123"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  application:
    name: giftu
    
    
security:
  jwt:
    token:
      secret-key: jwtGiftUSecretKey
      expire-length: 86400    
   